spring:
  datasource:
    url: jdbc:h2:file:../snippets
    driverClassName: org.h2.Driver

  h2:
    console.enabled: true
    console.settings:
      trace: false
      web-allow-others: false
  jpa.database-platform: org.hibernate.dialect.H2Dialect
